# Pandas Assignment

In [1]:
import pandas as pd

## Q1. Refer to googleplaystore.csv file and solve following questions.

In [2]:
data = pd.read_csv("C:/Users/ganes/OneDrive/Desktop/FBS/Database files/googleplaystore.csv")

### a. Display First 5 records from Dataframe.

In [3]:
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

### b. Display category with highest number of apps registered.

In [4]:
data['Category'].value_counts().idxmax()

'FAMILY'

### c. What is the average rating for all the apps

In [5]:
data['Rating'].mean()

np.float64(4.193338315362443)

### d. Display total number of apps which even supports Andriod version 2.3 and up

In [6]:
len(data[data['Android Ver'] == '2.3 and up'])

652

### e. Impute the missing values available in rating column with respective measure of central tendency.

In [7]:
data['Rating'] = data['Rating'].fillna(data['Rating'].mean())
data['Rating']

0        4.100000
1        3.900000
2        4.700000
3        4.500000
4        4.300000
           ...
10836    4.500000
10837    5.000000
10838    4.193338
10839    4.500000
10840    4.500000
Name: Rating, Length: 10841, dtype: float64

## Q2. Refer to salaries.xlsx file and solve following questions

In [8]:
dt = pd.read_excel("C:/Users/ganes/OneDrive/Desktop/FBS/Database files/Salaries.xlsx")

### a. Check head of the dataframe

In [9]:
dt.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

### b. Find out details about no. of entries & no. of columns in the data frame

In [10]:
dt.shape

(1000, 13)

### c. What is the average base pay?

In [11]:
dt['BasePay'].mean()

np.float64(145663.9982)

### d. What is the highest amount of overtime pay in the dataset?

In [15]:
dt['OvertimePay'].max()

np.float64(245131.88)

### e. What is the job title of JOSEPH DRISCOLL?

In [31]:
dt.loc[dt['EmployeeName'] == 'JOSEPH DRISCOLL',['EmployeeName', 'JobTitle']]

        EmployeeName                                        JobTitle
0    JOSEPH DRISCOLL  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1    JOSEPH DRISCOLL                 CAPTAIN III (POLICE DEPARTMENT)
2    JOSEPH DRISCOLL                 CAPTAIN III (POLICE DEPARTMENT)
3    JOSEPH DRISCOLL            WIRE ROPE CABLE MAINTENANCE MECHANIC
4    JOSEPH DRISCOLL    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
..               ...                                             ...
995  JOSEPH DRISCOLL                       CLINICAL NURSE SPECIALIST
996  JOSEPH DRISCOLL                       CLINICAL NURSE SPECIALIST
997  JOSEPH DRISCOLL                       CLINICAL NURSE SPECIALIST
998  JOSEPH DRISCOLL                       CLINICAL NURSE SPECIALIST
999  JOSEPH DRISCOLL                       CLINICAL NURSE SPECIALIST

[1000 rows x 2 columns]

### f. How much does JOSEPH DRISCOLL make (including benefits)?

In [35]:
dt.loc[dt['EmployeeName'] == 'JOSEPH DRISCOLL',['TotalPayBenefits']]

     TotalPayBenefits
0           567595.43
1           538909.28
2           335279.91
3           332343.61
4           326373.19
..                ...
995         169822.08
996         169822.06
997         169822.05
998         169822.01
999         169822.00

[1000 rows x 1 columns]

### g. How many unique job titles are there?

In [47]:
dt['JobTitle'].nunique()

113

### h. What are the top 5 common jobs?

In [49]:
dt['JobTitle'].value_counts()[0:5]

JobTitle
FIREFIGHTER                           133
LIEUTENANT, FIRE DEPARTMENT            62
FIRE FIGHTER PARAMEDIC                 43
CAPTAIN, FIRE SUPPRESSION              42
BATTALION CHIEF, (FIRE DEPARTMENT)     41
Name: count, dtype: int64